"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import { useDispatch, useSelector } from "react-redux";
import { AppDispatch, RootState } from "@/lib/store";
import { useEffect } from "react";
import { initializeState } from "@/lib/features/user/userSlice";
import Spinner from "@/components/Spinner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable}antialiased`}
      >
        <Providers>
          <AuthProvider>
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}

const AuthProvider = ({children}:Readonly<{children: React.ReactNode}>) => {
  const {isInitialized} = useSelector((state:RootState) => state.user);
  const dispatch = useDispatch<AppDispatch>();
  useEffect(() => {
    if(!isInitialized) {
      dispatch(initializeState());
    }
  },[])

  if(!isInitialized) {
    return <Spinner/>
  }
  return (
    <>{children}</>
  )
}
